pizzamama/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

pizzamama/menu/urls.py
from django.urls import path
from . import views

app_name = 'menu'

urlpatterns = [
    path('', views.index, name='index'),
]

pizzamama/pizzamama/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('menu/', include('menu.urls')),
    path('', include('main.urls')),
]

pizzamama/main/models.py
from django.db import models

# Create your models here.

pizzamama/menu/models.py
from django.db import models
"""
le model permet de creer les champs de donnees de notre application et bd
"""
class Pizza(models.Model):
    nom = models.CharField(max_length=200)
    ingredients = models.CharField(max_length=400)
    prix = models.FloatField(default=0)
    vegetarienne = models.BooleanField(default=False)

    def __str__(self):
        return self.nom

pizzamama/main/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):

    return render(request, 'main/index.html')

pizzamama/menu/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import Pizza

# Create your views here.
def index(request):
   """ pizzas = Pizza.objects.all()
    pizzas_names_price = [pizza.nom + " : " + str(pizza.prix) + "$" for pizza in pizzas]
    pizzas_names_price_str = ",".join(pizzas_names_price)
    return HttpResponse(f"les pizzas : {pizzas_names_price_str}")"""
   pizzas = Pizza.objects.all().order_by('prix')
   return render(request, 'menu/index.html', {"pizzas": pizzas})


pizzamama/main/templates/main/index.html
{% load static %}
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'main/style.css' %}">
    <title>Accueil</title>
</head>
<body>
    <div class="centered">
        <img class="main_logo" src="{% static 'main/images/main_logo.png' %}" alt="fond_ecran">
        <div>
           <a href="{% url 'menu:index'%}" target="_blank">Voir le menu</a>
        </div>
    </div>
</body>
</html>

pizzamama/menu/templates/menu/index.html

{% load static %}

<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Menu des pizzas</title>
    <link rel="stylesheet" href="{% static 'menu/style.css' %}">
</head>
<body>
    <a href="{% url 'main:index'%}"><img id="small_logo" src="{% static 'menu/images/small_logo.png' %}"></a>
    <div class="menu_title">
        <h1>Les pizzas</h1>
    </div>

    {% for pizza in pizzas %}
    <div class ="menu_list">
        <div class ="menu_list_item">

        <!-- | floatformat:# permet de donner le nombre de chiffre apres la virgule -->
            <span class="menu_list_title">{{pizza.nom}}</span> <span class="menu_list_price">{{pizza.prix | floatformat:2}}$</span>
            <span class="menu_list_ingredient">{{pizza.ingredients}} </span>

             {% if pizza.vegetarienne %}
                <span class="badge_vegetarien">VEGETARIENNE </span>
             {% endif %}
        </div>
    </div>
    {% endfor %}
</body>
</html>